### PR TITLE
newlib impls for some f32 fns

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by burrbull** [comment]
Ready for merge

**Comment by gnzlbg** [comment]
@japaric review ?

**Comment by burrbull** [comment]
bors try

**Comment by alexcrichton** [comment]
Sorry for the delay here @burrbull, and sorry for what's now a pretty big merge conflict :(

Would you still be interested in pursuing this? If so I think we should be in a position to merge this when ready!

**Comment by burrbull** [comment]
Closed, because it needs rework and split.

**Pull request closed without merging**
